### ISSUE TITLE
remove duplicate files?

### ISSUE THREAD

**Issue by sckott** [dagster-io/quickstart-gcp#1]
```
cd quickstart-gcp
tree | grep .py$
```

```
├── __init__.py
│   ├── __init__.py
│   └── hackernews.py
├── hackernews.py
├── io_managers.py
│   ├── __init__.py
│   │   ├── __init__.py
│   │   └── hackernews.py
│   ├── io_managers.py
│   └── repository.py
│   ├── __init__.py
│   └── test_assets.py
├── repository.py
├── setup.py
```

There's duplicates of hackernews.py, io_managers.py, and repository.py, where the duplicates I think have all the same code i them. AFAICT we only need the files in the quickstart_gcp module

**Comment by yuhan** [comment]
Hi @sckott thanks for opening the issue. It was an oversight. I've updated the files.
